; kernel
extern __kernelStart
extern __kernelEnd

; sections
extern __textSectStart
extern __textSectEnd

extern __dataSectStart
extern __dataSectEnd

extern __bssSectStart
extern __bssSectEnd

; text section
extern __loaderStart
extern __loaderEnd

extern __textStart
extern __textEnd

extern __rodataStart
extern __rodataEnd

; data section
extern __ctorsStart
extern __ctorsEnd

extern __dtorsStart
extern __dtorsEnd

extern __ehframeStart
extern __ehframeEnd

; bss section
extern __bssStart
extern __bssEnd

extern __commonStart
extern __commonEnd
